# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-26 13:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_auto_20180226_1329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={},
        ),
    ]
